### ISSUE TITLE
[FEATURE] getBlock by index API method

### ISSUE THREAD

**Issue by lailune** [Izzzio/izzzio#65]
> Hi! My name is Andrey and I'm glad to see you here :)
> 
> In this distribution, we are creating our open source blockchain platform. In development, we adhere to two main ideas: universatility and simplicity.
> 
> The technology should be as flexible as possible so that it can be easily used in different industries.
> 
> The technology should be simple enough so that everyone understands the basic principles of work and could use it without reading a ton of documentation.
> 
> If you are interested in the project, I suggest you solve one of the simple tasks, the description of which I added below. Join our community to make the world easier and better!
> 
> **Do not forget to ask questions in the comments on this issue. 
> I will tell you once how to solve this issue.**
> 
> Good luck! 

**Is your feature request related to a problem? Please describe.**
There is no way to request through API the contents of any block by index.

**Describe the solution you'd like**
API which returns content of the block in the JSON object by block index.

**Additional context**
Implementation must be done in [modules/frontend.js](https://github.com/Izzzio/izzzio/blob/master/modules/frontend.js) file

**To send an offer, create a Pull request in the master branch of the project.**

**Comment by vik7pol** [comment]
Can I work on it?

**Comment by lailune** [comment]
> Can I work on it? I would like to have more experience in js, and I think it will be good start.

Hi! 
You are welcome! You can ask questions of interest to you at any time
